scalar IntDict
scalar StringDict
scalar UserDict

type Query {
  getRoom(
    id: ID
    tag: String
  ): Room

  getUser(
    id: ID!
  ): User
}

type Mutation {
  makeRoom(
    tag: String!
  ): Room

  createUser(
    input: UserInput
  ): User

  updateUser(
    id: ID!
    input: UserInput!
  ): User

  joinRoom(
    room_id: ID!
    user_id: ID!
  ): Room

  proposeWord(
    room_id: ID!
    user_id: ID!
    word: String!
    definition: String!
  ): Word

  proposeDefinition(
    room_id: ID!
    user_id: ID!
    word_id: ID!
    definition: String!
  ): Definition

  submitVote(
    room_id: ID!
    user_id: ID!
    word_id: ID!
    def_id: ID!
  ): Definition
}

type User {
  id: ID!
  name: String
  color: String
}

input UserInput {
  name: String
  color: String
}

type Definition {
  id: ID!
  author: ID
  text: String
  voters: [ID!]!
}

enum WordStatus {
  PROPOSING
  VOTING
  CLOSED
}

type Word {
  id: ID!
  text: String
  author: ID
  comittee: [ID!]!
  definitions: [Definition!]!
  status: WordStatus!
}

type Room {
  id: ID!
  tag: String
  players: [ID!]!
  aliases: UserDict!
  words: [Word!]!
  scores: IntDict!
}

input RoomInput {
  tag: String
}
