type Query {
  getRoomById(id: ID!): Room
  getRoomByTag(tag: String!): Room
  getPlayerById(id: ID!): Player
}

type Mutation {
  createRoom(tag: String!): Room
  createPlayer: Player
}

type Player {
  _id: ID
  tag: String!
  color: String!
  overallScore: Int
}

type DefinitionTuple {
  id: ID!         # id of proposer
  value: String!  # definition
}

type VoteTuple {
  id: ID!         # id of voter
  proposerid: ID! # id of proposer to which the vote goes
}

type ScoreTuple {
  id: ID!         # id of player
  score: Int!     # score of the player
}

enum WordState {
  OPEN
  VOTING
  CLOSED
}

type Word {
  authorid: ID! # the author's id is used to find the 'true' definition
  voters: [ID!]!
  definitions: [DefinitionTuple!]!
  votes: [VoteTuple!]!
  state: WordState!
}

type Room {
  _id: ID
  tag: String!
  players: [Player!]!
  words: [Word!]!
  scores: [ScoreTuple!]!
}
